### ISSUE TITLE
Discussion: Approaches for typing

### ISSUE THREAD

**Issue by francisrstokes** [francisrstokes/hexnut#10]
The idea of this issue is to have an open discussion about how typing could be effectively implemented in the project, and understanding what the tradeoffs would be for any given solution.

**Comment by creatorrr** [comment]
Some approaches that come to mind :
 - port codebase to typescript / flow.js
 - add flow.js and typescript type defs separately and leave codebase as is

I'd personally lean towards the second one so as to not buy into any one ecosystem and since it doesn't affect the build process much. That said, this decision is affected by many factors up to you @francisrstokes

**Comment by moimikey** [comment]
i would +1 to separating the type defs. i think with open source libraries especially. when  implemented into a code base, the consumer could be using either typescript or flow. but double edged sword, maintaining two type defs... but alas, a solution https://github.com/joarwilk/flowgen -- write the defs in typescript (since, let's be honest here, it's more robust than Flow at  this point) and then autogen the flow defs as support.

**Comment by francisrstokes** [comment]
My primary goal with typing is to to improve the developers knowledge and confidence about the shape and behaviour of the `ctx` object as new middlewares are added. So if I have a middleware that adds a new method `sendJson` to the `ctx` object, and I run:

```javascript
app.use(addSendJsonMiddleware);

app.use((ctx, next) => {
 // Here I now have typing information about ctx.sendJson()
});
```

I know that this _should_ in theory be possible, provided the middleware developer is able to describe the changes somehow, but I am not knowledgable enough about typescript to know how to do it myself.

**Comment by creatorrr** [comment]
@francisrstokes we would need to write a Typescript "definition" file. Docs:
 - [Guide for library authors](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
 - [Template for global library interface](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html)
 - [Template for plugin interface](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-plugin-d-ts.html)
 - [What the plugin authors would need to do](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-plugin-d-ts.html)

**Comment by francisrstokes** [comment]
These are great resources @creatorrr, thanks for sharing! There are still some missing pieces for me - essentially how these typings can be progressively applied as the developer calls `app.use()` with different middleware, and how to tell the typescript complier that the new type is the result of all the calls to `app.use()` over time. This is the trickiest part I think!

A friend shared this piece of typescript with me, in which a class progressively refines it's type based on calls to one of it's methods:

```javascript
class QueryBuilder<model, result> {
  run = (): Promise<result> => null!;

  selectField = <field extends Exclude<keyof model, keyof result>>(field: field):
    QueryBuilder<model, result & { [x in field]: model[x] }> => null!
}

const q = new QueryBuilder<Person, {}>()
  .selectField('age')
  .selectField('kind')
  .selectField('name')
  .run();
```

I'm sure this example specifically is not going to work, but something in a similar vein utilising typescript features, alongside the examples you've shared should lead to something interesting.
